# Generated by Django 4.1.5 on 2023-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
