# Generated by Django 4.1.5 on 2023-01-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_date_created_menu_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_active',
        ),
    ]
