# Generated by Django 4.1.5 on 2023-01-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menugroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.menugroup'),
            preserve_default=False,
        ),
    ]
