# Generated by Django 4.1.5 on 2023-01-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_menuitem_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='variant',
            field=models.IntegerField(choices=[(0, 'Has Size'), (1, 'No Size')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurant.menuitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
