# Generated by Django 4.1.5 on 2023-01-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_active',
        ),
    ]
