# Generated by Django 4.1.5 on 2023-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Confirmed'), (2, 'Delivered'), (3, 'Canceled')], default=0),
        ),
    ]
